export enum WEBSOCKET_EVENTS {
  JOIN_ROOM = 'join_room',
  GET_MESSAGES = 'get_messages',
  SEND_MESSAGE = 'send_message',
  RECEIVE_MESSAGE = 'receive_message',
  NEW_MESSAGE = 'new_message',
  REMOVED_FROM_CLASSROOM = 'removed_from_classroom',
  ROOM_JOINED = 'room_joined',
  CHAT_ERROR = 'chat_error',
  NOTIFICATION = 'notification',
  NOTIFICATION_NEW = 'notification:new',
  WAITING_LIST_UPDATED = 'waiting_list_updated',
  PERTICIPENT_APPROVED = 'participant-approved',
  LIVE_SESSION_JOIN = 'live-session-join',
  WAITING_ROOM_UPDATED = 'waiting-room-updated',
  PARTICIPANT_APPROVED = 'participant-approved',
  PARTICIPANT_REMOVED = 'participant-removed',
  HAND_RAISED = 'hand-raised',
  MODERATION_COMMAND = 'moderation-command',
  SESSION_ENDED = 'session-ended',
  LIVE_CHAT_MESSAGE = 'live-chat-message',
}
